# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1350982149);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1350982269);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1350981431);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 204800);
user_pref("calendar.categories.names", "Affaire,Anniversaire,Appels,Cadeaux,Clients,Compétitions,Congés,Congrès,Consommation,Divers,Fournisseurs,Idées,Jour férié,Personnel,Préférés,Problèmes,Professionnel,Projets,Réunion,Suivis,Voyages");
user_pref("calendar.list.sortOrder", "0f0d9c4f-8bb5-4b96-8522-6b3be4c1a5c5");
user_pref("calendar.preferences.lightning.selectedTabIndex", 0);
user_pref("calendar.registry.0f0d9c4f-8bb5-4b96-8522-6b3be4c1a5c5.calendar-main-default", true);
user_pref("calendar.registry.0f0d9c4f-8bb5-4b96-8522-6b3be4c1a5c5.calendar-main-in-composite", true);
user_pref("calendar.registry.0f0d9c4f-8bb5-4b96-8522-6b3be4c1a5c5.name", "Home");
user_pref("calendar.registry.0f0d9c4f-8bb5-4b96-8522-6b3be4c1a5c5.type", "storage");
user_pref("calendar.registry.0f0d9c4f-8bb5-4b96-8522-6b3be4c1a5c5.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "UTC");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 13);
user_pref("extensions.enabledAddons", "{e2fda1a4-762b-4020-b5ad-a41df1933103}:1.8,{a62ef8ec-5fdc-40c2-873c-223b8a6925cc}:0.17,neo@acanac.net:2.3");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"edsintegration@mozilla.com\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/edsintegration@mozilla.com.xpi\",\"mtime\":1349911455000},\"messagingmenu@mozilla.com\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi\",\"mtime\":1349911455000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1350635881000}}},{\"name\":\"app-profile\",\"addons\":{\"neo@acanac.net\":{\"descriptor\":\"/home/netrunner/.thunderbird/so8mthku.default/extensions/neo@acanac.net.xpi\",\"mtime\":1350981864000},\"{35f30c40-35d4-11d9-8dbc-000c6e787ef9}\":{\"descriptor\":\"/home/netrunner/.thunderbird/so8mthku.default/extensions/{35f30c40-35d4-11d9-8dbc-000c6e787ef9}.xpi\",\"mtime\":1350981244000},\"{e2fda1a4-762b-4020-b5ad-a41df1933103}\":{\"descriptor\":\"/home/netrunner/.thunderbird/so8mthku.default/extensions/{e2fda1a4-762b-4020-b5ad-a41df1933103}\",\"mtime\":1350981219000},\"{a62ef8ec-5fdc-40c2-873c-223b8a6925cc}\":{\"descriptor\":\"/home/netrunner/.thunderbird/so8mthku.default/extensions/{a62ef8ec-5fdc-40c2-873c-223b8a6925cc}\",\"mtime\":1350982418000},\"riseofthetools@rsjtdrjgfuzkfg.com\":{\"descriptor\":\"/home/netrunner/.thunderbird/so8mthku.default/extensions/riseofthetools@rsjtdrjgfuzkfg.com.xpi\",\"mtime\":1350981091000},\"{2A95E724-F74E-46D3-93FD-3E9850382E52}\":{\"descriptor\":\"/home/netrunner/.thunderbird/so8mthku.default/extensions/{2A95E724-F74E-46D3-93FD-3E9850382E52}.xpi\",\"mtime\":1350981091000}}}]");
user_pref("extensions.lastAppVersion", "16.0.1");
user_pref("extensions.lastPlatformVersion", "16.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/theme");
user_pref("extensions.ui.locale.hidden", true);
user_pref("general.skins.selectedSkin", "oxygenate");
user_pref("gfx.blacklist.suggested-driver-version", "<Anything with EXT_texture_from_pixmap support>");
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.preferences.advanced.selectedTabIndex", 4);
user_pref("mail.preferences.display.selectedTabIndex", 1);
user_pref("mail.rights.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 4);
user_pref("mailnews.database.global.datastore.id", "77281085-0c3e-44ae-bd1a-a987e442736");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page.enabled", false);
user_pref("mailnews.start_page_override.mstone", "16.0.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("toolkit.telemetry.prompted", true);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
